### ISSUE TITLE
Добавить график downfall

### ISSUE THREAD

**Issue by dimonfofr** [approximatenumber/swallow_meteostation#3]

**Comment by approximatenumber** [comment]
@dimonfofr Если будешь еще добавлять описание, то будет еще круче

**Comment by approximatenumber** [comment]
@dimonfofr напиши плз про новый параметр (я про `deltageiger`, `maxWind`), исходящий от станции, что он точно значит, как считается... А то я забыл.

**Comment by approximatenumber** [comment]
Добавил.
