### ISSUE TITLE
Добавить ссылку на старый интерфейс

### ISSUE THREAD

**Issue by dimonfofr** [approximatenumber/swallow_meteostation#5]

**Comment by approximatenumber** [comment]
@dimonfofr а что, если из старого интерфейса будет только табличка с макс. и мин.?
без графиков, а чисто табличка

**Comment by dimonfofr** [comment]
@approximatenumber давай все, нупожалуйста

**Comment by approximatenumber** [comment]
@dimonfofr ладно, я уже делаю. но у меня почему-то всё показывается в чертовых фаренгейтах. ищу, где это поправить...

**Comment by approximatenumber** [comment]
@dimonfofr [see](http://swallowws.tk/)

**Comment by approximatenumber** [comment]
Done.
